#SERVER CONFIGURATION
server:
  port: 8080

#MySQL CONFIGURATIONS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daje
    username: daje
    password: daje
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      continue-on-error: false

pokemon:
  daje:
    external-base-path: ../src/main/resources/
    external-properties: properties-back-end.json