INSERT INTO type(pokedex_type_id, image_url, name) VALUES
                                                       (1, '/type_ice', 'ice'),
                                                       (2, '/type_ghost', 'ghost'),
                                                       (3, '/type_fairy', 'fairy'),
                                                       (4, '/type_dragon', 'dragon'),
                                                       (5, '/type_electric', 'electric'),
                                                       (6, '/type_rock', 'rock'),
                                                       (7, '/type_steel', 'steel'),
                                                       (8, '/type_fighting', 'fighting'),
                                                       (9, '/type_ground', 'ground'),
                                                       (10, '/type_poison', 'poison'),
                                                       (11, '/type_dark', 'dark'),
                                                       (12, '/type_fire', 'fire'),
                                                       (13, '/type_bug', 'bug'),
                                                       (14, '/type_psychic', 'psychic'),
                                                       (15, '/type_flying', 'flying'),
                                                       (16, '/type_grass', 'grass'),
                                                       (17, '/type_normal', 'normal'),
                                                       (18, '/type_water', 'water'),
                                                       (30000,'/type_unknown','unknown');